"""store forensic report on analysis case

Revision ID: 375d3992ba6b
Revises: 8d6f9cd8c5e1
Create Date: 2026-09-24 20:51:17.616328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '375d3992ba6b'
down_revision: Union[str, Sequence[str], None] = '8d6f9cd8c5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_cases', sa.Column('forensic_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_cases', 'forensic_report')
    # ### end Alembic commands ###
