"""initial email intelligence schema

Revision ID: 8d6f9cd8c5e1
Revises: 
Create Date: 2026-09-24 20:42:10.402074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '8d6f9cd8c5e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('recipient', sa.Text(), nullable=True),
    sa.Column('probable_origin_ip', sa.String(length=64), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_cases_analysis_id'), 'analysis_cases', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_analysis_cases_case_number'), 'analysis_cases', ['case_number'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=True)
    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ioc_type', 'value', name='uq_ioc_type_value')
    )
    op.create_table('analysis_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_task_id'), 'analysis_tasks', ['task_id'], unique=True)
    op.create_table('authentication_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('spf', sa.String(length=16), nullable=False),
    sa.Column('dkim', sa.String(length=16), nullable=False),
    sa.Column('dmarc', sa.String(length=16), nullable=False),
    sa.Column('alignment', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('campaign_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'ioc_id', 'case_id', name='uq_campaign_ioc_case')
    )
    op.create_table('domain_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('dns_records', sa.JSON(), nullable=False),
    sa.Column('mx_records', sa.JSON(), nullable=False),
    sa.Column('hosting_information', sa.JSON(), nullable=False),
    sa.Column('lookalike', sa.Boolean(), nullable=False),
    sa.Column('matched_brand', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_indicators_case_id'), 'domain_indicators', ['case_id'], unique=False)
    op.create_table('email_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_email_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_email_size', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_reference', sa.Text(), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_evidence_case_id'), 'email_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_email_evidence_raw_email_hash'), 'email_evidence', ['raw_email_hash'], unique=False)
    op.create_table('email_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('from_address', sa.Text(), nullable=True),
    sa.Column('to_address', sa.Text(), nullable=True),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('reply_to', sa.Text(), nullable=True),
    sa.Column('return_path', sa.Text(), nullable=True),
    sa.Column('date_header', sa.Text(), nullable=True),
    sa.Column('mime_info', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('header_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('identity_mismatch', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=True),
    sa.Column('reply_to_domain', sa.String(length=255), nullable=True),
    sa.Column('return_path_domain', sa.String(length=255), nullable=True),
    sa.Column('received_headers', sa.JSON(), nullable=False),
    sa.Column('relay_count', sa.Integer(), nullable=False),
    sa.Column('probable_origin_ip', sa.String(length=64), nullable=True),
    sa.Column('authentication_results', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('ip_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.String(length=64), nullable=True),
    sa.Column('reverse_dns', sa.String(length=255), nullable=True),
    sa.Column('reputation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_indicators_case_id'), 'ip_indicators', ['case_id'], unique=False)
    op.create_table('url_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('scheme', sa.String(length=16), nullable=True),
    sa.Column('suspicious_keywords', sa.JSON(), nullable=False),
    sa.Column('ip_based', sa.Boolean(), nullable=False),
    sa.Column('obfuscation_indicators', sa.JSON(), nullable=False),
    sa.Column('shortener', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_indicators_case_id'), 'url_indicators', ['case_id'], unique=False)
    op.create_table('evidence_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['email_evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_events')
    op.drop_index(op.f('ix_url_indicators_case_id'), table_name='url_indicators')
    op.drop_table('url_indicators')
    op.drop_index(op.f('ix_ip_indicators_case_id'), table_name='ip_indicators')
    op.drop_table('ip_indicators')
    op.drop_table('header_analyses')
    op.drop_table('email_metadata')
    op.drop_index(op.f('ix_email_evidence_raw_email_hash'), table_name='email_evidence')
    op.drop_index(op.f('ix_email_evidence_case_id'), table_name='email_evidence')
    op.drop_table('email_evidence')
    op.drop_index(op.f('ix_domain_indicators_case_id'), table_name='domain_indicators')
    op.drop_table('domain_indicators')
    op.drop_table('campaign_indicators')
    op.drop_table('authentication_results')
    op.drop_index(op.f('ix_analysis_tasks_task_id'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    op.drop_table('iocs')
    op.drop_index(op.f('ix_campaigns_campaign_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analysis_cases_case_number'), table_name='analysis_cases')
    op.drop_index(op.f('ix_analysis_cases_analysis_id'), table_name='analysis_cases')
    op.drop_table('analysis_cases')
    # ### end Alembic commands ###
