"""persist case IOC relationships

Revision ID: dfa76ff49e59
Revises: 375d3992ba6b
Create Date: 2026-09-24 21:04:36.558816
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'dfa76ff49e59'
down_revision: Union[str, Sequence[str], None] = '375d3992ba6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'ioc_id', name='uq_case_ioc')
    )
    op.create_index(op.f('ix_case_iocs_case_id'), 'case_iocs', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_iocs_ioc_id'), 'case_iocs', ['ioc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_iocs_ioc_id'), table_name='case_iocs')
    op.drop_index(op.f('ix_case_iocs_case_id'), table_name='case_iocs')
    op.drop_table('case_iocs')
    # ### end Alembic commands ###
