"""add risk alerts

Revision ID: e5812e2ff755
Revises: dfa76ff49e59
Create Date: 2026-09-24 21:09:32.162999
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e5812e2ff755'
down_revision: Union[str, Sequence[str], None] = 'dfa76ff49e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['analysis_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'alert_type', name='uq_alert_case_type')
    )
    op.create_index(op.f('ix_alerts_case_id'), 'alerts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_case_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
